"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rfek3ta@)n=k!_%bjgupj(jgwvx!o&6_rg4fejck1+5_fh%t*t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS: list[str] = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat',
]

AUTH_USER_MODEL = 'chat.User'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'compose'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# PostgreSQL per the project constitution (Technology Stack). Defaults match
# the local dev provisioning (`createuser --createdb strophae`, db `strophae`);
# override via POSTGRES_* environment variables in other environments.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'strophae'),
        'USER': os.environ.get('POSTGRES_USER', 'strophae'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'strophae'),
        'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'

# UI languages offered to users. English is the source language embedded in
# code/templates and the fallback for any missing translation; adding a
# language here (plus its locale/ catalog) is all it takes to offer it.
LANGUAGES = [
    ('en', 'English'),
    ('it', 'Italiano'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

# The language cookie is the device-level choice for signed-out visitors; it
# must outlive the browser session (Django's default is a session cookie).
LANGUAGE_COOKIE_AGE = 60 * 60 * 24 * 365

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# OpenRouter models offered in the per-agent selector.
OPENROUTER_MODELS = [
    'GPT-4o', 'GPT-4o mini', 'o3', 'Claude Opus 4.1', 'Claude Sonnet 4',
    'Gemini 2.5 Pro', 'Llama 3.3 70B', 'DeepSeek 4 Flash', 'DeepSeek V3',
    'Mistral Large',
]

# Display label -> OpenRouter model slug for real streaming calls.
OPENROUTER_MODEL_SLUGS = {
    'GPT-4o': 'openai/gpt-4o',
    'GPT-4o mini': 'openai/gpt-4o-mini',
    'o3': 'openai/o3',
    'Claude Opus 4.1': 'anthropic/claude-opus-4.1',
    'Claude Sonnet 4': 'anthropic/claude-sonnet-4',
    'Gemini 2.5 Pro': 'google/gemini-2.5-pro',
    'Llama 3.3 70B': 'meta-llama/llama-3.3-70b-instruct',
    'DeepSeek 4 Flash': 'deepseek/deepseek-v4-flash',
    'DeepSeek V3': 'deepseek/deepseek-chat',
    'Mistral Large': 'mistralai/mistral-large',
}
